### ISSUE TITLE
Chat not connecting in some cases

### ISSUE THREAD

**Issue by Austin1011** [the-obsidian/DiscordBridge#1]
Hello,

Just wanted to say great plugin it works perfect on my own private server hosted right from my computer. I am having some issues getting it to connect on a dedicated server hosted with Intreppid.

I know this issue is on my end with my host but I was wondering if you could shed some insight on what is needed to allow communication through. Ports, security, etc.

Thanks so much!

**Comment by jacobwgillespie** [comment]
Interesting - I can do some more digging.  @NotGGhost, the guy who wrote the lower-level API may have some insight, but I believe it opens a websocket connection which should be on a standard http/https port 80/443, but it is an upgrade on the HTTP protocol and is a persistent connection, so maybe that's triggering some firewall somewhere.  It's an outgoing connection, so as far as I know you shouldn't need any incoming ports/protocols to be unblocked.

I suppose you could check with Intreppid on websocket connection issues.

**Comment by NotGGhost** [comment]
The websocket api I'm using has issues with their certificates, so currently uses port 80, and a range of different hostnames for the socket server, which are currently under the pattern of `gateway-*.discord.gg`. 

Try running these commands:

Command: `wget https://discordapp.com/api/auth/login  --post-data="email=YourDiscordEmail&password=YourDiscordPassword" && nano login`
Sample output: http://itsghost.me/SuW8Cv

Command: `ping gateway-fafnir.discord.gg -p 80`
Sample output: http://itsghost.me/tKOmRZ

**Comment by jacobwgillespie** [comment]
I'm going to close this for now - feel free to ping if you're still running into any issues.
