### ISSUE TITLE
Messages being shown twice, three times..

### ISSUE THREAD

**Issue by maxerium** [the-obsidian/DiscordBridge#10]
Everytime you reload the server, the plugin builds up a new connection but doesn't close the old one.
What happens, is, that after every reload it adds one more line.

Without a reload:
[Discord] DiscordUser123: Hi.

With 1 reload:
[Discord] DiscordUser123: Hi.
[Discord] DiscordUser123: Hi.

With 2 reloads:
[Discord] DiscordUser123: Hi.
[Discord] DiscordUser123: Hi.
[Discord] DiscordUser123: Hi.

And so on! Please fix that. :+1:

**Comment by jacobwgillespie** [comment]
This is expected if you're reloading with `/reload` - that isn't supported in most plugins actually.  With the upcoming release of version 1.4, you can reload Discord specifically with `/discord reload`, but `/reload` will always be unsupported.

**Comment by mouro001** [comment]
Jacob, you need to onDisable to disable the plugin. (I just know the basics)
