### ISSUE TITLE
Compatibility with the Vanish plugin.

### ISSUE THREAD

**Issue by chrisk123999** [the-obsidian/DiscordBridge#11]
A popular plugin for may Spigot / Craftbukkit servers is the plugin called VanishNoPacket.   It makes moderating a server much easier and allows players with the right permissions to be invisible in-game and on the server list.  Currently this plugin will  end up showing  when vanished players join the server in Discord.  Would it be possible to integrate with VanishNoPacket's API to not send join and leave messages for vanished players?  Their github is here: https://github.com/mbax/VanishNoPacket

**Comment by jacobwgillespie** [comment]
Thanks for the suggestion - I just released v1.5.0 which integrates with VNP - you can choose (using the `is_vanished` setting) whether to send chat messages, join message, leave messages, or death messages for users who are vanished.
