### ISSUE TITLE
Death Messsages

### ISSUE THREAD

**Issue by chrisk123999** [the-obsidian/DiscordBridge#12]
Should be fairly simple.  Currently death messages aren't shown in Discord and it's sometimes relevant to the the discussion.

**Comment by jacobwgillespie** [comment]
This has been added as an optional message in v1.4.0: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0.  You should adjust `settings.messages.death` in config.yml after the plugin is updated.
