### ISSUE TITLE
Support for nicknames.

### ISSUE THREAD

**Issue by HelmicNewciv** [the-obsidian/DiscordBridge#13]
Nickname mods are popular, nicks are what people are actually known by on a server.  Displaying someone's Minecraft nickname on Discord would be helpful for identifying who is who.  Obviously keep the option of displaying someone's real username as well.

**Comment by jacobwgillespie** [comment]
This has been added in v1.4.0: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0.  You can use `%d` in the message templates to get access to the user's display name.
