### ISSUE TITLE
Reload Option

### ISSUE THREAD

**Issue by SilverKytten** [the-obsidian/DiscordBridge#15]
I know, I know. Not good for servers.

It's fairly annoying to have to restart the entire server to see if an edit works or not, or even to reconnect to the discord chat if they've done updates or the connection has gone wonky; especially if you're running a lot of mods, as well.

**Comment by jacobwgillespie** [comment]
This has been added (`/discord reload`) in v1.4.0: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0
