### ISSUE TITLE
"Error occurred while enabling DiscordBridge v1.3.0"

### ISSUE THREAD

**Issue by TheMentalist10** [the-obsidian/DiscordBridge#17]
Just installed, but it's [throwing this error every time I launch](http://pastebin.com/bqqayiAP). It's configured according to instructions as far as I can see!

[Here's the config file](http://i.imgur.com/BusDp77.png) with personal information blacked-out. I did notice that the single quotes are lacking from some (and present in the installation), but I tried adding them and they were removed when I next rebooted.

Thanks!

**Comment by chrisk123999** [comment]
Update your Java.  This plugin requires Java 8.

**Comment by TheMentalist10** [comment]
Thanks for letting me know. Sadly, it's third-party hosted and so I can't update Java myself, but I appreciate your response!

**Comment by jacobwgillespie** [comment]
Yeah, contact your host.  At this point, everybody should be running Java 8 for security reasons.
