### ISSUE TITLE
Discord bot offline in chat, errors in console

### ISSUE THREAD

**Issue by Paul--** [the-obsidian/DiscordBridge#18]
Hi there!
Great work on the plugin so far - this is a solid piece of work!

Yesterday, about 16 hours ago, I was running DiscordBridge with no problems. Our designated bot was sending and receiving Discord and Minecraft chat with no dramas - happily ever after and all that jazz.

About 2 hours ago, upon coming back to the server, the Discord bot was logged out and chat wasn't sending. This is normal and has happened multiple times before. I normally fix it with a restart - which of course I tried immediately. The bot remained offline. I now get the following message on repeat:

DiscordAPI: Attempting go log in <again?>!
DiscordAPI: Shutting down!
DiscordAPI: Attempting to login!
DiscordAPI: Logged in and starting session!
DiscordAPI: Token: <very long alphanumeric string here, made of three dotted decimal sections - the first two of which are always the same, the third of which changes with each 'attempt'.>
WARN: Internal client error!

This occurs in the space of about 2 seconds for a loop, with about 25-30 seconds between 'attempts'.

The server is running on 1.8 Spigot with v1.3.0 DiscordBridge.

I have tried:
Multiple restarts.
Removing DiscordBridge and letting it generate a new config.yml.
Logging into my Discord bot account manually (works as normal).
Banging my head on the desk (sadly no results).

I will also add that nothing on the server was changed from the time DiscordBridge worked to the time it didn't. No players were online, no updates were performed. Nothing.

Thanks for taking the time to read this and looking forward to hearing a solution!

**Comment by KingTorm** [comment]
Having the same problem with my servers, since it's not just me my best guess is that something changed with Discord's servers.

**Comment by Paul--** [comment]
Good to know it's not just me!

**Comment by Pawned** [comment]
Also got the same issue, most likely changes with Discord have stopped the official unofficial API from working properly.

**Comment by rdlenk** [comment]
Same here, great plugin, I hope it can be fixed.

**Comment by xDeeKay** [comment]
Same issue here.

**Comment by jacobwgillespie** [comment]
Yeah, I need to update the underlying Discord API library in use here (to be more specific, I need to replace it with another better maintained library).  I should get to that later today.

**Comment by Paul--** [comment]
Thanks for the update Jacob - looking forward to using the plugin again.

**Comment by shoginyan** [comment]
it's not working for me either. sad

**Comment by xDeeKay** [comment]
@popcorn230 https://github.com/Scarsz/DiscordSRV works amazingly and constantly updated.

**Comment by DiscordMan05** [comment]
Oh, this is frequent for me. It's been happening with my Napstabot. Strangely, the bot 'Streams' on Twitch, and decides to go Offline, where I am blocked from using my own bot. I don't know how long this lasts, but I surely hope they fix this.
