### ISSUE TITLE
Plugin isnt sending messages to Discord

### ISSUE THREAD

**Issue by mouro001** [the-obsidian/DiscordBridge#19]
Isnt sending messages neither recieving from discord.

**Comment by jacobwgillespie** [comment]
This is a duplicate of #18 - I should have a fix out shortly

**Comment by mouro001** [comment]
just a question, how shortly? if it is 1 day, max 2 i will wait, if not i will move to slack

**Comment by jacobwgillespie** [comment]
v1.4.0 is out now and should fix the issue: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0
