### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by NotGGhost** [the-obsidian/DiscordBridge#2]
>Ability to post messages to Discord on behalf of Discord users, rather than using a bot user (hopefully after the official API is released)

This is possible using the account manager 
```java
 api.getAccountManager().setDisplayName(event.getPlayer().getDisplayName());```

**Comment by jacobwgillespie** [comment]
It's possible for the bot account to impersonate another user? Or would the
bot need the login info for the impersonated users?

**Comment by NotGGhost** [comment]
No relogging is required inorder to do this. Impersonation is as easy as calling the set display name method, and once you've done that, newer messages will appear to be from the new alias, whilst older ones will stay. Restarting the discord client might effect the display name though.

**Comment by jacobwgillespie** [comment]
Okay, yeah, did some experimentation - it's close but doesn't look like it'll cut it.  

First, username changes aren't propagated to the clients immediately, so if you want to change the username, and send a message, you have to delay.  

Second, the client gets pretty confused about who's sending what message - it shows something like:

**Old Username:**
message
message

**New Username**
one message

And after every new message it moves the one message above under the old username.

Anyways, it's close but until Discord allows for proper display names and avatars per message (a la Slack), it looks like this feature will have to wait.

Thanks @NotGGhost for the help!
