### ISSUE TITLE
Messages from discord being sent to minecraft after unload

### ISSUE THREAD

**Issue by Limeth** [the-obsidian/DiscordBridge#24]
When the plugin is unloaded or disabled, messages from the discord channel are still being sent to the minecraft server.

**Comment by jacobwgillespie** [comment]
How are you unloading or disabling the plugin?

**Comment by Limeth** [comment]
I have a PluginManager plugin, which manages manual loading, unloading, enabling and disabling of other plugins via commands.

**Comment by jacobwgillespie** [comment]
Okay, I'll take a look if I get a chance, though in general this plugin won't support being unloaded or disabled without a server restart.

**Comment by jacobwgillespie** [comment]
This might be fixed by #47 - I'm closing for now, but feel free to post back if `v2.0` has the same issue.
