### ISSUE TITLE
Discord messages aren't being displayed

### ISSUE THREAD

**Issue by tylerking** [the-obsidian/DiscordBridge#29]
Messages in Minecraft display just fine but any messages typed in Discord don't show up on the server. Did I miss something?

**Comment by jacobwgillespie** [comment]
What's your config file look like (without the password)?

**Comment by tylerking** [comment]
So I had a friend test with me and I can see their messages coming from Discord but not mine. Is this by design? Here is my config:

settings:
  server-id: '152955122115280907'
  channel: lobby
  username: doitliketyler
  email: 
  password: 
  debug: false
  relay_cancelled_messages: true
  messages:
    join: true
    leave: true
    death: true
  templates:
    discord:
      chat_message: <&6M-&r%u> %m
      player_join: '&a%u joined the server'
      player_leave: '&7%u left the server'
      player_death: '&4%r'
    minecraft:
      chat_message: <&bD-&r%u> %m
version: 1.4.5

**Comment by jacobwgillespie** [comment]
Yep, that's by design. You'll want to have a separate user for your bot on Discord and use that username and password in the config. The plugin automatically filters out messages from its own username so that there isn't a message loop (minecraft to discord then back to minecraft etc.)

**Comment by tylerking** [comment]
Ah ok. Makes perfect sense. Thanks for you help.

**Comment by jacobwgillespie** [comment]
No prob!
