### ISSUE TITLE
Can you please update it, for the Discord API Login with token :)

### ISSUE THREAD

**Issue by KyoshiHikari** [the-obsidian/DiscordBridge#31]
Hey that was very nice to update it for Login with Token, but i created a Discord Bot with the official API and need now to login with a token.

Regards Kiyo

**Comment by jacobwgillespie** [comment]
Hey, thanks for this, I've started on a rewrite to support the official API.

**Comment by jacobwgillespie** [comment]
Can you test this with v1.7.0 and let me know if it works for you? https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.7.0

You add a setting next to email and password called `token` with the bot token - more details in the README.

**Comment by KyoshiHikari** [comment]
Hey :D 

Yeah Tested with Token and yes it works, not testet the other things but bot logged in with token :D

Regard Kiyo 

```
Jacob Gillespie <notifications@github.com> schrieb am 16:41 Montag, 18.April 2016:
```

 Can you test this with v1.7.0 and let me know if it works for you? https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.7.0You add a setting next to email and password called token with the bot token - more details in the README.—
