### ISSUE TITLE
Player leave message

### ISSUE THREAD

**Issue by ezenity** [the-obsidian/DiscordBridge#32]
When a player leaves console outputs a error

![Leave Message Error](https://i.imgur.com/t1UHZzw.png)

**Comment by ezenity** [comment]
Actually it breaks everything, for me to fix this I would have to restart the server. Reload command wont fix it. Not sure if this is on my end or the plugins.

**Comment by jacobwgillespie** [comment]
It's likely an issue with updating the Discord client library - let me do that and get a test build for you.

**Comment by jacobwgillespie** [comment]
Looks like the official Discord API is out now - I've got a bit of rewriting to do but this should be done shortly.

**Comment by jacobwgillespie** [comment]
Can you test this with v1.7.0? https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.7.0

**Comment by ezenity** [comment]
Sure thing, I will do it now and let you know how it goes.
