### ISSUE TITLE
file changing when rebooting

### ISSUE THREAD

**Issue by FutureMagick** [the-obsidian/DiscordBridge#35]
I'm adding jar to server and rebooting server and shutting it down again and putting config in and rebooting and the configs changing to this I have set this up on another server and its fine

[config getting from server.txt](https://github.com/the-obsidian/DiscordBridge/files/235571/config.getting.from.server.txt)
[config upload to the server.txt](https://github.com/the-obsidian/DiscordBridge/files/235572/config.upload.to.the.server.txt)

**Comment by FutureMagick** [comment]
seems to be working now even tho it changed the file lol

**Comment by jacobwgillespie** [comment]
Cool 👍
