### ISSUE TITLE
If password begins with 0 in config, DiscordBridge moves the 0 to the end and adds a decimal

### ISSUE THREAD

**Issue by Okramto** [the-obsidian/DiscordBridge#37]
For example;

Before DiscordBridge is loaded:

password: 05478

After DiscordBridge is loaded:

password: 5478.0

This results in an error.

`Error connecting to Discord: javax.security.auth.login.LoginException: The provided email / password combination was incorrect. Please provide valid details.`

**Comment by jacobwgillespie** [comment]
Try adding quotes, like this and it should work:

`password: "05478"`

**Comment by Okramto** [comment]
Can't believe I didn't try that. It works. You are just on an issue closing roll right now ;)
