### ISSUE TITLE
[Suggestion] You can create a mod in the future?

### ISSUE THREAD

**Issue by Eufranio** [the-obsidian/DiscordBridge#38]
I have an 1.8.9 and i can't use Sponge, then, can someone create a mod of this in future?

**Comment by jacobwgillespie** [comment]
This works with Bukkit / Spigot on the server side (as a plugin) - it wouldn't really work as a mod.  There's no Sponge version yet

**Comment by Eufranio** [comment]
In 1.7.10, DiscordChat worked as a mod forge, but no longer updated. About Sponge, I talked about the current sponge plugins, but I do not use sponge...

**Comment by jacobwgillespie** [comment]
Gotcha - I haven't seen DiscordChat before - I'll have to check it out.

**Comment by Eufranio** [comment]
http://mods.curse.com/mc-mods/minecraft/240995-discordchat
