### ISSUE TITLE
Update Discord API client

### ISSUE THREAD

**Issue by jbdman** [the-obsidian/DiscordBridge#39]
Hi,

Messages will not get forwarded to within the discord from in game.  I would attempt to fix this myself, but I am just starting in plugin coding. I am getting the error as follows:

<code>18.06 21:38:32 [Server] INFO [DiscordBridge] Received a chat event from SheepPuncher651: yes please
18.06 21:38:32 [Server] INFO [DiscordBridge] Sending message to Discord - <SheepPuncher651> yes please
18.06 21:38:32 [Server] ERROR Could not pass event AsyncPlayerChatEvent to DiscordBridge v1.7.1
18.06 21:38:32 [Server] INFO org.bukkit.event.EventException
18.06 21:38:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1111) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1026) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
18.06 21:38:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
18.06 21:38:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
18.06 21:38:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
18.06 21:38:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
18.06 21:38:32 [Server] INFO Caused by: net.dv8tion.jda.exceptions.PermissionException: Cannot preform action due to a lack of Permission. Missing permission: MESSAGE_WRITE
18.06 21:38:32 [Server] INFO at net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:152) ~[?:?]
18.06 21:38:32 [Server] INFO at net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:144) ~[?:?]
18.06 21:38:32 [Server] INFO at gg.obsidian.discordbridge.DiscordConnection.send(DiscordConnection.kt:30) ~[?:?]
18.06 21:38:32 [Server] INFO at gg.obsidian.discordbridge.Plugin.sendToDiscord(Plugin.kt:30) ~[?:?]
18.06 21:38:32 [Server] INFO at gg.obsidian.discordbridge.EventListener.onChat(EventListener.kt:39) ~[?:?]
18.06 21:38:32 [Server] INFO at sun.reflect.GeneratedMethodAccessor527.invoke(Unknown Source) ~[?:?]
18.06 21:38:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
18.06 21:38:32 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
18.06 21:38:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
18.06 21:38:32 [Server] INFO ... 12 more

Send</code>

**Comment by jbdman** [comment]
Oops, I just realized that this is a Discord issue, .......

**Comment by jacobwgillespie** [comment]
Yep, Discord issue - I'm reopening to remind myself to update the API client library we use internally here.

**Comment by DiamondIceNS** [comment]
I assume this is resolved in #47 right? We're on JDA 3.0 now.

**Comment by jacobwgillespie** [comment]
Should be fixed, yep - closing.  🎉
