### ISSUE TITLE
Duplicate messages between Discord and Server

### ISSUE THREAD

**Issue by daytonmills** [the-obsidian/DiscordBridge#42]
Whenever somebody types in the game chat,
The Bot will put that message into the discord channel.
Although when it does, the message the bot put into chat then goes to Minecraft.

To clarify:
1.) In Minecraft chat I say "Hi"
2.) Instantly the bot puts my game message into the text channel on Discord.
3.) The bot message in that channel is then sent into Minecraft chat.
![capture](https://cloud.githubusercontent.com/assets/11009428/20586104/74e2f1a6-b1c6-11e6-896a-116e8ed55661.PNG)

**Comment by daytonmills** [comment]
Is there a way to not send bot messages into the game chat?

**Comment by jacobwgillespie** [comment]
What's in your `settings.yml`?  The `username` setting is used to filter out bot messages from being sent back to Minecraft.  It should probably be `ProperBot` from your screenshot.

**Comment by daytonmills** [comment]
Ah, I had the numbers after the username...
I removed the numbers and it works perfectly.

**Comment by jacobwgillespie** [comment]
Nice, glad it's working now!  👍
