### ISSUE TITLE
Repeated messages.

### ISSUE THREAD

**Issue by inthenightsky** [the-obsidian/DiscordBridge#43]
Hey there,

Recently got your plugin setup - nice job by the way.

However, it seems to repeat the messages someone sends in game and put them back into the chat. Is there a way this can be altered?

Example: https://puu.sh/tb943/70a4d993a4.png

**Comment by jacobwgillespie** [comment]
Thanks!  The username setting needs to be the username of the bot user, without the numbers.  So:

```yaml
username: dankcraft-bot
```

**Comment by inthenightsky** [comment]
Sorted that, but now the messages from Minecraft > Discord won't sync. They'll do it the other way around though.

I've got debugging enabled, and chat events are being received.

**Comment by inthenightsky** [comment]
Apparently just needed a reboot of the server, not a reload.

**Comment by jacobwgillespie** [comment]
Ah, cool, glad you got it sorted.  I'm pretty sure the plugin doesn't correctly tolerate reloads, so a restart makes sense.
