### ISSUE TITLE
Minecraft -> Discord using bot: Message shows up twice in MC

### ISSUE THREAD

**Issue by gjerm** [the-obsidian/DiscordBridge#44]
If a player sends a message in the Minecraft chat, it will correctly show up in Discord. The bot will also pick its own message up and relay it back to Minecraft again, essentially duplicating every message.

Here's an example:
![Duplicate message](http://i.imgur.com/rCwaRyl.png)

Perhaps it would be possible to have a list of ignored usernames from the Discord side?

**Comment by LividJava** [comment]
does this persist after a server restart??

**Comment by gjerm** [comment]
Yup.

**Comment by jacobwgillespie** [comment]
There is a an ignored username setting in the `config.yml` and that's `username`.  You'll want it to be your Discord user's username without the numbers or pound sign.  For you, that's likely:

```yaml
username: CCBridge
```

**Comment by gjerm** [comment]
Yeah, I must have read the documentation too quickly. Sorry.

**Comment by jacobwgillespie** [comment]
No prob - glad it's working for you!
