### ISSUE TITLE
Bot sending messages to the MC server twice

### ISSUE THREAD

**Issue by oolivero45** [the-obsidian/DiscordBridge#51]
Whenever someone speaks on Discord, the bot sends two copies of the message to the server.

Screenshot:
![image](https://user-images.githubusercontent.com/16722292/27927914-28f9be58-6285-11e7-9620-946c829bbd6b.png)

**Comment by oolivero45** [comment]
Additionally, it seems like for one of the two messages it uses the template defined in the config file, and the other it uses the one that was there from the default config.

**Comment by jacobwgillespie** [comment]
If you restart your server (restart, not reload) that should fix the issue - it looks like the plugin's reload command is not properly terminating the old version of itself, hence the two messages with different configurations.  A full restart should fix for now.

**Comment by oolivero45** [comment]
Just tried what you suggested, and it fixed the problem for me. Thanks!
