### ISSUE TITLE
Suggestion - Minecraft Command Fowarding

### ISSUE THREAD

**Issue by LividJava** [the-obsidian/DiscordBridge#54]
If possible i want to know if there is a way to push console commands from discord
IE
`Discord User <prefix> time set day
Console output:
<Discord Username> Executed <Command>`
or something similar i can see where this would create issues with  attempting to sync minecraft usernames with discord usernames but it would make it easier to moderate my server on the go without having to either go in game or use something like minechat

**Comment by DiamondIceNS** [comment]
Implemented in #58
