### ISSUE TITLE
[not an issue]  Can I use this for my own discord bot (with credit)

### ISSUE THREAD

**Issue by doronseg** [the-obsidian/DiscordBridge#57]
I have a bot called MC-Manager.
Witch is currently has only server-status command and ip command 
i wish that i had this minecraft chat thing but I don't know if i can get this code.
we can also collaborate and merge the bot.
or I can get this code.
Thanks,
Doron

**Comment by DiamondIceNS** [comment]
This project is licensed under MIT license. In general, what that means is you have free right to copy, modify, and distribute the code as long as you:

1. Include our copyright notice in your project and
2. Include a readable copy of our LICENSE.TXT in your project
