### ISSUE TITLE
Forge version?

### ISSUE THREAD

**Issue by awade33** [the-obsidian/DiscordBridge#6]
Hi, I'm not really sure where to ask but I was wondering if there was a forge version of this mod? My server is not using bukkit/spigot because it was causing some really weird issues with our pack but we'd really like to connect our discord chat and our mc chat. Even something as simple as relaying all the chat in a channel back and forth would be great.

**Comment by jacobwgillespie** [comment]
Yep, this is the correct place to ask - I'm not really familiar with making Forge mods, and to do so would require a rewrite of the code.  It's definitely something I'd consider making in the future (I'd probably make a "core" plugin with adapters for Bukkit, Sponge, and Forge), though my time is limited so I'm not sure when that'd be.

I'll close this for now but the request has been noted.  :+1:
