### ISSUE TITLE
The provided email / password combination was incorrect. when using a token

### ISSUE THREAD

**Issue by RedBlaze42** [the-obsidian/DiscordBridge#64]
Hello !
I love your great plugin but my server wont use it:
Here is the log:
[log](https://pastebin.com/raw/R6fp4SuS)
And here the config file:
[config.yml](https://pastebin.com/raw/Za1BuwVd)

**Comment by DiamondIceNS** [comment]
You're using a very old version of DiscordBridge. I suggest updating to the latest version, [4.0.0](https://github.com/the-obsidian/DiscordBridge/releases/tag/v4.0.0), which is the currently maintained version that has a wealth of more features.

If you want to keep using v1.7.1 though, replace your config.yml with [this version](https://github.com/the-obsidian/DiscordBridge/blob/88e3aa27946bd94a1413b9dcfdd4dadc6ed643dc/src/main/resources/config.yml). The config format you have now is for a later version of the plugin and is incompatible.

**Comment by RedBlaze42** [comment]
Thx it works
