### ISSUE TITLE
Ignore cancelled chat events

### ISSUE THREAD

**Issue by optical** [the-obsidian/DiscordBridge#7]
Hi,

Currently the plugin relays all chat messages. This is a problem if we want to cancel a chat message because it contains bad language, is spam, goes to a private channel, or a variety of other reasons.

I think it'd be wise to allow users to configure whether cancelled chat events get relayed. This way those using no channel system but some filtering (spam prevention, etc) can still cancel the message, while those using a channel system which cancel all messages can continue to use the bridge.

Essentially what I am proposing is a config option for relaying cancelled messages. If this sounds fine, I'll open up a PR

**Comment by optical** [comment]
Since the change was minimal I've created the PR already.

**Comment by jacobwgillespie** [comment]
Closed by #8
