### ISSUE TITLE
Discord Bot disconnects

### ISSUE THREAD

**Issue by RedZephon** [the-obsidian/DiscordBridge#9]
Occasionally the account (bot) I have setup to relay minecraft chat to discord will go offline in discord. However it continues to transmit minecraft chat from Minecraft to Discord but you can't see any chat from Discord into Minecraft without rebooting the server (and thus restarting the bot)

Can you also add a /db reload command?

**Comment by jacobwgillespie** [comment]
The plugin should automatically reconnect on disconnect in v1.4.0: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0.  There is also a new `/discord reload` command that will reload the config and reconnect to Discord.
